In [3]:
import numpy as np

**Задание 1**

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [2]:
def create_array_desc_sort(N):
    a = np.arange(0, N)
    a[::-1].sort()
    return a

create_array_desc_sort(10)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [6]:
a = np.arange(0, 10)
a[::-1].sort()

In [7]:
a

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

**Задание 2**

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [26]:
def create_diag_array_desc_sort(N):
    b = np.diag(np.arange(N), k=0)
    # sum_diag = 0
    for i, value in enumerate(b): # индекс вложенного списка всегда будет соответствовать индексу нужного элемента в нем
        b[i,i] = (N-1) - b[i,i]
    #     sum_diag += b[i,i]
    # print(b)
    # print(sum_diag)
    return b
# create_diag_array_desc_sort(10)

In [28]:
def main(N):
    array_ = create_diag_array_desc_sort(N)
    sum_diag = np.diag(array_).sum()
    return sum_diag
main(15)

105

**Задание 3**

Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [38]:
# коэффициенты при переменных в левой части уравнения
a = np.array( [ [4, 2, 1], [1, 3, 0], [5, 0, 4] ] )

In [39]:
# значения в правой части уравнения
b = np.array( [4, 12, -3] )

In [40]:
# решение
from numpy import linalg

In [41]:
linalg.solve(a, b)

array([-1.56,  4.52,  1.2 ])

In [42]:
# проверка верности
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

**Доп. задание из лекции**

Имеется матрица покупок в интернет-магазине. Строка - посетитель, столбцы - количество покупок категорий товаров посетителем.

Матрица в виде numpy array: users_stats

На сайт заходит очередной посетитель, о покупках которого известно следующее: next_user_stats = np.array([0, 1, 2, 0, 0, 0])
    
Найти самого похожего пользователя (посчитать косинусное расстояние между этим пользователем и всеми пользователями из массива user_stats)


In [4]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [5]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [8]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])
i = 0
max_similar = 0
id_similar = 0

res = []

for user in users_stats:
    cur_ = np.array(user)
    next_ = next_user_stats
    similar = cosine(cur_, next_)
    if similar > max_similar:
        max_similar = similar
        id_similar = i
    i += 1
    
    res.append(max_similar)
    
print('Самый похожий посетитель сайта - в строке с индексом:', res.index(max_similar))
print('Косинусное расстояние: ' "%.2f" %(max_similar))
# res

Самый похожий посетитель сайта - в строке с индексом: 7
Косинусное расстояние: 0.95
